### ISSUE TITLE
这个包看着还不错，预计什么时候发布正式版本？

### ISSUE THREAD

**Issue by kbdxbt** [guanguans/laravel-api-response#1]

**Comment by guanguans** [comment]
@kbdxbt 最近有点忙，所以耽搁了，我会尽快发布的。预计这个月底之前应该能发布吧，不过不能完全保证哦，还是以主业为主 :smile: 。

**Comment by guanguans** [comment]
@kbdxbt 1.0.0 正式版已发布，欢迎使用，及时反馈问题和意见。
